export const SET_UI = 'SET_UI';
export const HYDRATE = 'HYDRATE';

export const LOAD_CURRENT_USER_REQUEST = 'LOAD_CURRENT_USER_REQUEST';
export const LOAD_CURRENT_USER_SUCCESS = 'LOAD_CURRENT_USER_SUCCESS';
export const LOAD_CURRENT_USER_FAILURE = 'LOAD_CURRENT_USER_FAILURE';

export const UPDATE_CURRENT_USER_REQUEST = 'UPDATE_CURRENT_USER_REQUEST';
export const UPDATE_CURRENT_USER_SUCCESS = 'UPDATE_CURRENT_USER_SUCCESS';
export const UPDATE_CURRENT_USER_FAILURE = 'UPDATE_CURRENT_USER_FAILURE';

export const LOAD_COMMANDS_REQUEST = 'LOAD_COMMANDS_REQUEST';
export const LOAD_COMMANDS_SUCCESS = 'LOAD_COMMANDS_SUCCESS';
export const LOAD_COMMANDS_FAILURE = 'LOAD_COMMANDS_FAILURE';

export const CREATE_COMMAND_REQUEST = 'CREATE_COMMAND_REQUEST';
export const CREATE_COMMAND_SUCCESS = 'CREATE_COMMAND_SUCCESS';
export const CREATE_COMMAND_FAILURE = 'CREATE_COMMAND_FAILURE';

export const UPDATE_COMMAND_REQUEST = 'UPDATE_COMMAND_REQUEST';
export const UPDATE_COMMAND_SUCCESS = 'UPDATE_COMMAND_SUCCESS';
export const UPDATE_COMMAND_FAILURE = 'UPDATE_COMMAND_FAILURE';

export const DELETE_COMMAND_REQUEST = 'DELETE_COMMAND_REQUEST';
export const DELETE_COMMAND_SUCCESS = 'DELETE_COMMAND_SUCCESS';
export const DELETE_COMMAND_FAILURE = 'DELETE_COMMAND_FAILURE';

export const LOAD_TIMERS_REQUEST = 'LOAD_TIMERS_REQUEST';
export const LOAD_TIMERS_SUCCESS = 'LOAD_TIMERS_SUCCESS';
export const LOAD_TIMERS_FAILURE = 'LOAD_TIMERS_FAILURE';

export const CREATE_TIMER_REQUEST = 'CREATE_TIMER_REQUEST';
export const CREATE_TIMER_SUCCESS = 'CREATE_TIMER_SUCCESS';
export const CREATE_TIMER_FAILURE = 'CREATE_TIMER_FAILURE';

export const UPDATE_TIMER_REQUEST = 'UPDATE_TIMER_REQUEST';
export const UPDATE_TIMER_SUCCESS = 'UPDATE_TIMER_SUCCESS';
export const UPDATE_TIMER_FAILURE = 'UPDATE_TIMER_FAILURE';

export const DELETE_TIMER_REQUEST = 'DELETE_TIMER_REQUEST';
export const DELETE_TIMER_SUCCESS = 'DELETE_TIMER_SUCCESS';
export const DELETE_TIMER_FAILURE = 'DELETE_TIMER_FAILURE';
