export const SET_UI = 'SET_UI';
export const HYDRATE = 'HYDRATE';

export const LOAD_CURRENT_USER_REQUEST = 'LOAD_CURRENT_USER_REQUEST';
export const LOAD_CURRENT_USER_SUCCESS = 'LOAD_CURRENT_USER_SUCCESS';
export const LOAD_CURRENT_USER_FAILURE = 'LOAD_CURRENT_USER_FAILURE';

export const UPDATE_CURRENT_USER_REQUEST = 'UPDATE_CURRENT_USER_REQUEST';
export const UPDATE_CURRENT_USER_SUCCESS = 'UPDATE_CURRENT_USER_SUCCESS';
export const UPDATE_CURRENT_USER_FAILURE = 'UPDATE_CURRENT_USER_FAILURE';

export const LOAD_COMMANDS_REQUEST = 'LOAD_COMMANDS_REQUEST';
export const LOAD_COMMANDS_SUCCESS = 'LOAD_COMMANDS_SUCCESS';
export const LOAD_COMMANDS_FAILURE = 'LOAD_COMMANDS_FAILURE';

export const CREATE_COMMAND_REQUEST = 'CREATE_COMMAND_REQUEST';
export const CREATE_COMMAND_SUCCESS = 'CREATE_COMMAND_SUCCESS';
export const CREATE_COMMAND_FAILURE = 'CREATE_COMMAND_FAILURE';

export const UPDATE_COMMAND_REQUEST = 'UPDATE_COMMAND_REQUEST';
export const UPDATE_COMMAND_SUCCESS = 'UPDATE_COMMAND_SUCCESS';
export const UPDATE_COMMAND_FAILURE = 'UPDATE_COMMAND_FAILURE';

export const DELETE_COMMAND_REQUEST = 'DELETE_COMMAND_REQUEST';
export const DELETE_COMMAND_SUCCESS = 'DELETE_COMMAND_SUCCESS';
export const DELETE_COMMAND_FAILURE = 'DELETE_COMMAND_FAILURE';

export const LOAD_TIMERS_REQUEST = 'LOAD_TIMERS_REQUEST';
export const LOAD_TIMERS_SUCCESS = 'LOAD_TIMERS_SUCCESS';
export const LOAD_TIMERS_FAILURE = 'LOAD_TIMERS_FAILURE';

export const CREATE_TIMER_REQUEST = 'CREATE_TIMER_REQUEST';
export const CREATE_TIMER_SUCCESS = 'CREATE_TIMER_SUCCESS';
export const CREATE_TIMER_FAILURE = 'CREATE_TIMER_FAILURE';

export const UPDATE_TIMER_REQUEST = 'UPDATE_TIMER_REQUEST';
export const UPDATE_TIMER_SUCCESS = 'UPDATE_TIMER_SUCCESS';
export const UPDATE_TIMER_FAILURE = 'UPDATE_TIMER_FAILURE';

export const DELETE_TIMER_REQUEST = 'DELETE_TIMER_REQUEST';
export const DELETE_TIMER_SUCCESS = 'DELETE_TIMER_SUCCESS';
export const DELETE_TIMER_FAILURE = 'DELETE_TIMER_FAILURE';

export const LOAD_DOTA_OVERLAY_REQUEST = 'LOAD_DOTA_OVERLAY_REQUEST';
export const LOAD_DOTA_OVERLAY_SUCCESS = 'LOAD_DOTA_OVERLAY_SUCCESS';
export const LOAD_DOTA_OVERLAY_FAILURE = 'LOAD_DOTA_OVERLAY_FAILURE';

export const UPDATE_DOTA_OVERLAY_REQUEST = 'UPDATE_DOTA_OVERLAY_REQUEST';
export const UPDATE_DOTA_OVERLAY_SUCCESS = 'UPDATE_DOTA_OVERLAY_SUCCESS';
export const UPDATE_DOTA_OVERLAY_FAILURE = 'UPDATE_DOTA_OVERLAY_FAILURE';

export const LOAD_GOOGLE_FONTS_REQUEST = 'LOAD_GOOGLE_FONTS_REQUEST';
export const LOAD_GOOGLE_FONTS_SUCCESS = 'LOAD_GOOGLE_FONTS_SUCCESS';
export const LOAD_GOOGLE_FONTS_FAILURE = 'LOAD_GOOGLE_FONTS_FAILURE';

export const LOAD_BET_SEASONS_REQUEST = 'LOAD_BET_SEASONS_REQUEST';
export const LOAD_BET_SEASONS_SUCCESS = 'LOAD_BET_SEASONS_SUCCESS';
export const LOAD_BET_SEASONS_FAILURE = 'LOAD_BET_SEASONS_FAILURE';

export const CREATE_BET_SEASON_REQUEST = 'CREATE_BET_SEASON_REQUEST';
export const CREATE_BET_SEASON_SUCCESS = 'CREATE_BET_SEASON_SUCCESS';
export const CREATE_BET_SEASON_FAILURE = 'CREATE_BET_SEASON_FAILURE';

export const UPDATE_BET_SEASON_REQUEST = 'UPDATE_BET_SEASON_REQUEST';
export const UPDATE_BET_SEASON_SUCCESS = 'UPDATE_BET_SEASON_SUCCESS';
export const UPDATE_BET_SEASON_FAILURE = 'UPDATE_BET_SEASON_FAILURE';

export const DELETE_BET_SEASON_REQUEST = 'DELETE_BET_SEASON_REQUEST';
export const DELETE_BET_SEASON_SUCCESS = 'DELETE_BET_SEASON_SUCCESS';
export const DELETE_BET_SEASON_FAILURE = 'DELETE_BET_SEASON_FAILURE';

export const LOAD_BET_SEASON_INVITES_REQUEST = 'LOAD_BET_SEASON_INVITES_REQUEST';
export const LOAD_BET_SEASON_INVITES_SUCCESS = 'LOAD_BET_SEASON_INVITES_SUCCESS';
export const LOAD_BET_SEASON_INVITES_FAILURE = 'LOAD_BET_SEASON_INVITES_FAILURE';

export const LOAD_BET_SEASON_USERS_REQUEST = 'LOAD_BET_SEASON_USERS_REQUEST';
export const LOAD_BET_SEASON_USERS_SUCCESS = 'LOAD_BET_SEASON_USERS_SUCCESS';
export const LOAD_BET_SEASON_USERS_FAILURE = 'LOAD_BET_SEASON_USERS_FAILURE';

export const LOAD_BET_SEASON_TOPLIST_REQUEST = 'LOAD_BET_SEASON_TOPLIST_REQUEST';
export const LOAD_BET_SEASON_TOPLIST_SUCCESS = 'LOAD_BET_SEASON_TOPLIST_SUCCESS';
export const LOAD_BET_SEASON_TOPLIST_FAILURE = 'LOAD_BET_SEASON_TOPLIST_FAILURE';

export const LOAD_BET_ROUNDS_REQUEST = 'LOAD_BET_ROUNDS_REQUEST';
export const LOAD_BET_ROUNDS_SUCCESS = 'LOAD_BET_ROUNDS_SUCCESS';
export const LOAD_BET_ROUNDS_FAILURE = 'LOAD_BET_ROUNDS_FAILURE';

export const CREATE_BET_ROUND_REQUEST = 'CREATE_BET_ROUND_REQUEST';
export const CREATE_BET_ROUND_SUCCESS = 'CREATE_BET_ROUND_SUCCESS';
export const CREATE_BET_ROUND_FAILURE = 'CREATE_BET_ROUND_FAILURE';

export const UPDATE_BET_ROUND_REQUEST = 'UPDATE_BET_ROUND_REQUEST';
export const UPDATE_BET_ROUND_SUCCESS = 'UPDATE_BET_ROUND_SUCCESS';
export const UPDATE_BET_ROUND_FAILURE = 'UPDATE_BET_ROUND_FAILURE';

export const DELETE_BET_ROUND_REQUEST = 'DELETE_BET_ROUND_REQUEST';
export const DELETE_BET_ROUND_SUCCESS = 'DELETE_BET_ROUND_SUCCESS';
export const DELETE_BET_ROUND_FAILURE = 'DELETE_BET_ROUND_FAILURE';

export const LOAD_STEAM_CONNECTIONS_REQUEST = 'LOAD_STEAM_CONNECTIONS_REQUEST';
export const LOAD_STEAM_CONNECTIONS_SUCCESS = 'LOAD_STEAM_CONNECTIONS_SUCCESS';
export const LOAD_STEAM_CONNECTIONS_FAILURE = 'LOAD_STEAM_CONNECTIONS_FAILURE';

export const RESET_DOTA_GSI_REQUEST = 'RESET_DOTA_GSI_REQUEST';
export const RESET_DOTA_GSI_SUCCESS = 'RESET_DOTA_GSI_SUCCESS';
export const RESET_DOTA_GSI_FAILURE = 'RESET_DOTA_GSI_FAILURE';

export const LOAD_CURRENT_BET_ROUND_REQUEST = 'LOAD_CURRENT_BET_ROUND_REQUEST';
export const LOAD_CURRENT_BET_ROUND_SUCCESS = 'LOAD_CURRENT_BET_ROUND_SUCCESS';
export const LOAD_CURRENT_BET_ROUND_FAILURE = 'LOAD_CURRENT_BET_ROUND_FAILURE';

export const AUTH_USER_REQUEST = 'AUTH_USER_REQUEST';
export const AUTH_USER_SUCCESS = 'AUTH_USER_SUCCESS';
export const AUTH_USER_FAILURE = 'AUTH_USER_FAILURE';

export const LOAD_BET_OVERLAY_REQUEST = 'LOAD_BET_OVERLAY_REQUEST';
export const LOAD_BET_OVERLAY_SUCCESS = 'LOAD_BET_OVERLAY_SUCCESS';
export const LOAD_BET_OVERLAY_FAILURE = 'LOAD_BET_OVERLAY_FAILURE';

export const UPDATE_BET_OVERLAY_REQUEST = 'UPDATE_BET_OVERLAY_REQUEST';
export const UPDATE_BET_OVERLAY_SUCCESS = 'UPDATE_BET_OVERLAY_SUCCESS';
export const UPDATE_BET_OVERLAY_FAILURE = 'UPDATE_BET_OVERLAY_FAILURE';

export const LOAD_ROSH_OVERLAY_REQUEST = 'LOAD_ROSH_OVERLAY_REQUEST';
export const LOAD_ROSH_OVERLAY_SUCCESS = 'LOAD_ROSH_OVERLAY_SUCCESS';
export const LOAD_ROSH_OVERLAY_FAILURE = 'LOAD_ROSH_OVERLAY_FAILURE';

export const UPDATE_ROSH_OVERLAY_REQUEST = 'UPDATE_ROSH_OVERLAY_REQUEST';
export const UPDATE_ROSH_OVERLAY_SUCCESS = 'UPDATE_ROSH_OVERLAY_SUCCESS';
export const UPDATE_ROSH_OVERLAY_FAILURE = 'UPDATE_ROSH_OVERLAY_FAILURE';

export const LOAD_CASTER_OVERLAY_REQUEST = 'LOAD_CASTER_OVERLAY_REQUEST';
export const LOAD_CASTER_OVERLAY_SUCCESS = 'LOAD_CASTER_OVERLAY_SUCCESS';
export const LOAD_CASTER_OVERLAY_FAILURE = 'LOAD_CASTER_OVERLAY_FAILURE';

export const UPDATE_CASTER_OVERLAY_REQUEST = 'UPDATE_CASTER_OVERLAY_REQUEST';
export const UPDATE_CASTER_OVERLAY_SUCCESS = 'UPDATE_CASTER_OVERLAY_SUCCESS';
export const UPDATE_CASTER_OVERLAY_FAILURE = 'UPDATE_CASTER_OVERLAY_FAILURE';

export const LOAD_DOTA_STATS_REQUEST = 'LOAD_DOTA_STATS_REQUEST';
export const LOAD_DOTA_STATS_SUCCESS = 'LOAD_DOTA_STATS_SUCCESS';
export const LOAD_DOTA_STATS_FAILURE = 'LOAD_DOTA_STATS_FAILURE';

export const REMOVE_DOTA_STATS_REQUEST = 'REMOVE_DOTA_STATS_REQUEST';
export const REMOVE_DOTA_STATS_SUCCESS = 'REMOVE_DOTA_STATS_SUCCESS';
export const REMOVE_DOTA_STATS_FAILURE = 'REMOVE_DOTA_STATS_FAILURE';

export const REMOVE_ALL_DOTA_STATS_REQUEST = 'REMOVE_ALL_DOTA_STATS_REQUEST';
export const REMOVE_ALL_DOTA_STATS_SUCCESS = 'REMOVE_ALL_DOTA_STATS_SUCCESS';
export const REMOVE_ALL_DOTA_STATS_FAILURE = 'REMOVE_ALL_DOTA_STATS_FAILURE';

export const LOAD_ANTI_SNIPE_OVERLAY_REQUEST = 'LOAD_ANTI_SNIPE_OVERLAY_REQUEST';
export const LOAD_ANTI_SNIPE_OVERLAY_SUCCESS = 'LOAD_ANTI_SNIPE_OVERLAY_SUCCESS';
export const LOAD_ANTI_SNIPE_OVERLAY_FAILURE = 'LOAD_ANTI_SNIPE_OVERLAY_FAILURE';

export const UPDATE_ANTI_SNIPE_OVERLAY_REQUEST = 'UPDATE_ANTI_SNIPE_OVERLAY_REQUEST';
export const UPDATE_ANTI_SNIPE_OVERLAY_SUCCESS = 'UPDATE_ANTI_SNIPE_OVERLAY_SUCCESS';
export const UPDATE_ANTI_SNIPE_OVERLAY_FAILURE = 'UPDATE_ANTI_SNIPE_OVERLAY_FAILURE';
